openapi: 3.0.0
info:
  title: Mini AI Studio API
  version: 1.0.0
  description: API for AI image generation studio

servers:
  - url: http://localhost:3001
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
          format: email

    Generation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        prompt:
          type: string
        style:
          type: string
          enum: [realistic, artistic, anime, sketch]
        imageUrl:
          type: string
          description: URL to the generated image
        originalImageUrl:
          type: string
          description: URL to the original uploaded image
        status:
          type: string
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        error:
          type: string
        retryable:
          type: boolean

paths:
  /auth/signup:
    post:
      summary: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/login:
    post:
      summary: Login to existing account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "401":
          description: Invalid credentials

  /generations:
    post:
      summary: Create a new generation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
                - prompt
                - style
              properties:
                image:
                  type: string
                  format: binary
                prompt:
                  type: string
                  maxLength: 500
                style:
                  type: string
                  enum: [realistic, artistic, anime, sketch]
      responses:
        "201":
          description: Generation created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Generation"
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                prompt: "A beautiful sunset"
                style: "realistic"
                imageUrl: "/uploads/550e8400-e29b-41d4-a716-446655440000.jpg"
                originalImageUrl: "/uploads/original-550e8400-e29b-41d4-a716-446655440000.jpg"
                status: "completed"
                createdAt: "2024-01-15T10:30:00.000Z"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "503":
          description: Model overloaded (retryable)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      summary: Get recent generations
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 5
      responses:
        "200":
          description: List of generations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Generation"
        "401":
          description: Unauthorized
